#!/bin/sh

masspy_dir=$( cd "$(dirname "$0")/../../" ; pwd -P )
cd $masspy_dir
for to_clean in '.*__pycache__' '.*ipynb_checkpoints' '.*log' ; do \
    find . -type d -regex $to_clean | xargs rm -rf ;
    done


# Clean coverage files
for to_clean in '.*coverage.*' '.coverage' ; do \
    find . -type f -regex $to_clean | xargs rm -rf
    done


# Clean test models generated by docs
for to_clean in '*.xml' '*.json'  '*.lp'; do \
    find ./docs -type f -name $to_clean | xargs rm -rf ;
    done
