#!/bin/sh

masspy_dir=$( cd "$(dirname "$0")/../../" ; pwd -P )
for to_clean in '.*__pycache__' '.*ipynb_checkpoints' '.*log' ; do \
    find $masspy_dir -type d -regex $to_clean | xargs rm -rf ;
    done

# Clean test models generated by docs
for to_clean in '*.xml' '*.json' ; do \
    find $masspy_dir/docs -type f -name $to_clean | xargs rm -rf ;
    done
