minimum_pre_commit_version: '1.15.0'
default_language_version:
    python: python3
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ['--django']
      - id: trailing-whitespace
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.7.0
      hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
    - repo: https://github.com/pycqa/isort
      rev: 5.6.4
      hooks:
      - id: isort
    - repo: https://github.com/psf/black
      rev: stable
      hooks:
      - id: black
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
      - id: flake8
