minimum_pre_commit_version: '2.9.0'
default_language_version:
    python: python3
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ['--django']
      - id: trailing-whitespace
        exclude: setup.cfg
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
      - id: python-check-blanket-noqa
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
    # - repo: https://github.com/mgedmin/check-manifest
    #   rev: "0.46"
    #   hooks:
    #   - id: check-manifest
    #     args: [--no-build-isolation]
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
      - id: isort
    - repo: https://github.com/psf/black
      rev: 21.12b0
      hooks:
      - id: black
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      - id: flake8
