[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.black]
line-length = 88
python-version = ['py36', 'py37']


[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
indent = 4
lines_after_imports = 2


[tool.tox]
legacy_tox_ini = """
[tox]
envlist = isort, black, flake8, safety, py37, docs


[gh-actions]
python =
    3.6: isort, black, flake8, safety, py36, docs
    3.7: safety, py37, docs


[testenv]
deps =
    pytest


[testenv:isort]
skip_install = True
deps =
    isort
commands =
    isort -c --diff {toxinidir}/src/mass {toxinidir}/setup.py


[testenv:black]
skip_install = True
deps =
    black
commands =
    black --check --diff --color {toxinidir}/src/mass {toxinidir}/setup.py


[testenv:flake8]
skip_install = True
deps =
    flake8
commands =
    flake8 {toxinidir}/src/mass {toxinidir}/setup.py


[testenv:safety]
deps =
    safety
commands =
    safety check --full-report


[testenv:docs]
extras =
    docs


[flake8]
ignore = E203, E266, E501, W503, F401
max-line-length = 88
max-complexity = 18


"""
