[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.black]
line-length = 88
python-version = ['py36', 'py37']


[tool.isort]
profile = "black"
src_paths = ["src/mass"]
indent = 4
lines_after_imports = 2


[tool.tox]
legacy_tox_ini = """
[tox]
minversion = 3.20
envlist = lint,
          safety,
          py36,
          py37,
          docs
isolated_build = true
skip_missing_interpreters = true



[gh-actions]
python =
    3.6: lint, safety, py36, docs
    3.7: safety, py37, docs


[testenv]
description = run the tests with pytest under {basepython}
deps =
    pytest


[testenv:lint]
description = lint code using pre-commit hook to activate isort, black, and flake8
passenv = *
skip_install = true
deps =
    pre-commit
commands =
    pre-commit install
    pre-commit run -a --show-diff-on-failure


[testenv:safety]
description = safety check installed dependencies for known security vulnerabilities.
deps =
    safety
commands =
    safety check --full-report


[testenv:docs]
description = build sphinx documentation
sitepackages=true
extras =
    docs
allowlist_externals =
    make
commands =
    make -C {toxinidir}/docs html

"""
