name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        id: checkout
        uses: actions/checkout@v2
      -
        name: Setup Python
        id: setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      -
        name: Lint using Black
        id: setup
        uses: psf/black@stable
