# name: Publish Docker image
# on:
#   push:
#     branches:
#       - master
#     tags:
#       - 'v.*.*'
# jobs:
  # push_to_registries:
  #   name: Push Docker image to multiple registries
  #   runs-on: ubuntu-latest
  #   services:
  #     registry:
  #       image: registry:2
  #       ports:
  #         - 5000:5000
  #   steps:
  #     - 
  #       name: Checkout
  #       id: checkout
  #       uses: actions/checkout@v2
  #     -
  #       name: Set up Docker Buildx
  #       id: docker-buildx-setup
  #       uses: docker/setup-buildx-action@v1
  #       with:
  #         driver-opts: network=host
  #     - 
  #       name: Build and push to local registry
  #       uses: docker/build-push-action@v2
  #       with: 
  #         push: true
  #     - 
  #       name: Inspect
  #       run: |
  #         docker buildx imagetools inspect localhost:5000/sbrg/masspy:latest

    
  #   - 
  #     name: Login to DockerHub
  #     id: docker-login
  #     uses: docker/login-action@v1
  #     with:
  #       registry: docker.io
  #       username: ${{ secrets.SBRG_MACHINE_USERNAME_DOCKERHUB }}
  #       password: ${{ secrets.SBRG_MACHINE_DOCKERHUB_TOKEN }}

    # - 
    #   name: Login to GitHub Container Registry
    #   id: ghcr-login
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ secrets.SBRG_MACHINE_USERNAME_GITHUB }}
    #     password: ${{ secrets.SBRG_MACHINE_GHCR_TOKEN }}