name: Publish Docker images
on:
  push:
    tags:
      - '^v[0-9]+.[0-9]+.[0-9]+$'

env:
  DOCKER_IMAGE: sbrg/masspy

jobs:
  push-to-registries:
    name: Build and push Docker images to registries
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        id: checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker-meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
            ghcr.io/${{ env.DOCKER_IMAGE }}
          tag-sha: true
          tag-match: '[0-9]+.[0-9]+.[0-9]+'  # e.g., v{MAJOR}.{MINOR}.{PATCH}
      -
        name: Set up Docker Buildx
        id: docker-buildx-setupx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        id: docker-login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SBRG_MACHINE_USERNAME_DOCKERHUB }}
          password: ${{ secrets.SBRG_MACHINE_DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        id: ghcr-login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.SBRG_MACHINE_USERNAME_GITHUB }}
          password: ${{ secrets.SBRG_MACHINE_GHCR_TOKEN }}
      -
        name: Build and push image to registry
        id: docker-build-push
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
