name: Publish Docker images
on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  push-to-registries:
    name: Build and push Docker images to registries
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - 
        name: Prepare image tag
        id: prep-tags
        run: |
          DOCKER_IMAGE="sbrg/masspy"
          if [[ "$GITHUB_REF" == "refs/tags/*" ]] ; then
            VERSION=$( echo $GITHUB_REF | sed 's/refs\/tags\///g' )
          elif [[ "$GITHUB_REF" == "refs/heads/${{ github.event.repository.default_branch }}" ]] ; then 
            VERSION=latest
          else
            exit 1
          fi
          TAGS=${DOCKER_IMAGE}:${VERSION}
          echo ::set-output name=tags::${TAGS}
      - 
        name: Set up Docker Buildx
        id: docker-buildx-setupx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        id: docker-login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SBRG_MACHINE_USERNAME_DOCKERHUB }}
          password: ${{ secrets.SBRG_MACHINE_DOCKERHUB_TOKEN }}
      - 
        name: Build and push image to registry
        id: docker-build-push
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.prep-tags.outputs.tags }}
