name: Upload Python Package to PyPi
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-and-deploy:
    name: Publish packages to the Python Packaging Index (PyPi)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]
    steps:
      - 
        name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - 
        name: Setup Python
        id: setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - 
        name: Install dependencies
        id: install-deps
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - 
        name: Build distribitions
        id: build-distribitions
        run: |
          python setup.py sdist bdist_wheel
      -
        name: Publish distribution to Test PyPI
        id: test-publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/
    #   -
        # name: Publish distribution to PyPI
        # id: publish
        # uses: pypa/gh-action-pypi-publish@master
        # with:
        #   user: ${{ secrets.PYPI_USERNAME }}
        #   password: ${{ secrets.PYPI_PASSWORD }}
